apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecom-app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ecom-app
  template:
    metadata:
      labels:
        app: ecom-app
    spec:
      containers:
        - name: ecom-app
          image: jenishchauhan/multibranch-python-app:build-6
          ports:
            - containerPort: 5000
